package com.techsophy.tsf.services.gateway.constants;

import lombok.AccessLevel;
import lombok.NoArgsConstructor;

@NoArgsConstructor(access = AccessLevel.PRIVATE)
public class GatewayTestConstants
{
    public static final String KIMS="KIMS";
    public static final String TECHSOPHY_PLATFORM="techsophy-platform";
    public static final String BEARER_TOKEN="Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJ2X2NzTUtiOVFsUVpETUg2TXBUdXV1YURtUWstVTQ3bmZjWVZGbFlpLTMwIn0.eyJleHAiOjE2ODM3MjE4MDIsImlhdCI6MTY4MzcyMDAwMiwianRpIjoiMWQzNTBhMDQtMDA5YS00MjJkLTk0NWItZjM4YTk4MmE4YzkxIiwiaXNzIjoiaHR0cHM6Ly9rZXljbG9hay10c3BsYXRmb3JtLnRlY2hzb3BoeS5jb20vYXV0aC9yZWFsbXMvdGVjaHNvcGh5LXBsYXRmb3JtIiwiYXVkIjpbImNhbXVuZGEtcmVzdC1hcGkiLCJyZWFsbS1tYW5hZ2VtZW50IiwidGlja2V0aW5nLXN5c3RlbSIsImFjY291bnQiXSwic3ViIjoiY2EwYjAzYjEtMjE3NS00YjI1LWI4NDYtNWYwYzlkNGQ4MWNiIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiY2FtdW5kYS1pZGVudGl0eS1zZXJ2aWNlIiwic2Vzc2lvbl9zdGF0ZSI6ImUxYzVkMmNmLTEyYjEtNDhjNi1iMWU0LWFkNTM4YzYyMDNhNSIsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOlsiKiIsImh0dHA6Ly9sb2NhbGhvc3Q6MzAwMSJdLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7InJlYWxtLW1hbmFnZW1lbnQiOnsicm9sZXMiOlsidmlldy1yZWFsbSIsInZpZXctaWRlbnRpdHktcHJvdmlkZXJzIiwibWFuYWdlLWlkZW50aXR5LXByb3ZpZGVycyIsImltcGVyc29uYXRpb24iLCJjcmVhdGUtY2xpZW50IiwibWFuYWdlLXVzZXJzIiwicXVlcnktcmVhbG1zIiwidmlldy1hdXRob3JpemF0aW9uIiwicXVlcnktY2xpZW50cyIsInF1ZXJ5LXVzZXJzIiwibWFuYWdlLWV2ZW50cyIsIm1hbmFnZS1yZWFsbSIsInZpZXctZXZlbnRzIiwidmlldy11c2VycyIsInZpZXctY2xpZW50cyIsIm1hbmFnZS1hdXRob3JpemF0aW9uIiwibWFuYWdlLWNsaWVudHMiLCJxdWVyeS1ncm91cHMiXX19LCJzY29wZSI6ImNhbXVuZGEtcmVzdC1hcGkgcHJvZmlsZSBlbWFpbCBhd2dtZW50IiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJuYW1lIjoidmFpYmhhdiBqYWlzd2FsIiwicHJlZmVycmVkX3VzZXJuYW1lIjoidmFpYmhhdiIsImdpdmVuX25hbWUiOiJ2YWliaGF2IiwiZmFtaWx5X25hbWUiOiJqYWlzd2FsIiwidXNlcklkIjoiMTA5NzQ5MzkwMzU0OTc0MzEwNCIsImVtYWlsIjoidmFpYmhhdi5rQHRlY2hzb3BoeS5jb20ifQ.aUeeEuKyxZ9ofyzzoDOSkd2N-lMMvpSpI5BmWfLWPhJXSJFP8ev5OmEnQukpeV7dxCDrmElNG8WQ4x4z7SIVDSg8G6uUOxUrIWb1gqeZxOfEMYP9cPsb3LrDZ5HopZVAxZ6xtnprJ80P2XmfiWnR0O1MnYP2pRBQwZxIOyNGpdTZWNqtL0-_Efl2OEhcVIjv8UDMsB7CGd3LA2bSH8M9b6Z908HYLYbU2PGjTM6zUSy5M9D0X1bAW1UrMiNxVczQ33HSvdkrGtHDBntOzlWCDR3OWRTU_uhix3I-qxvTfnoLS6nvUs8zDYOmgx5eSbth0m5zX3jFw94TVbKS1luEiA";
    public static final String TEST_URL="http://localhost:8080/";
    public static final String AUTHORIZATION="Authorization";
    public static final String RESPONSE_BODY="response body";
    public static final String CLIENT_ID="camunda-identity-service";
    public static final String CLIENT_SECRET="101";
    public static final String TESTING_TENANT="kims";
}
